apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-websphere-liberty-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM WebSphere Liberty Catalog
  image: icr.io/cpopen/websphere-liberty-operator-catalog@sha256:acb52ff0c00e37a8de858408b13b0ae4323f32d2188141b6a8792d12d89f0c0d
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
