apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-transadv-catalog
  namespace: openshift-marketplace
spec:
  displayName: "Transformation Advisor Catalog"
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-transformation-advisor-operator-catalog@sha256:2409b910cd6bdcd1fcb262df672be8f054ad60ce82254c7d51881030c2a884db
  updateStrategy:
    registryPoll:
      interval: 45m
